{
  "name": "RTSP to MJPEG Proxy",
  "version": "1.0.2",
  "slug": "rtsp2mjpg",
  "description": "Convert RTSP stream to MJPEG for use in Home Assistant",
  "startup": "services",
  "boot": "auto",
  "arch": ["aarch64", "amd64", "armv7"],
  "options": {
    "rtsp_url": "rtsp://example.com/stream"
  },
  "schema": {
    "rtsp_url": "str"
  },
  "ports": {
    "8080/tcp": 8080
  },
  "webui": "http://[HOST]:[PORT:8080]"
}